[Package]
name = 'core'
version = "0.1.0"

[[Bin]]
type = 'StaticLib'
name = 'core'
src = ['./src/io/', './src/memory/', './src/string/', './src/containers/', 'src/thread']
lang = 'C11'
opt_level = 'O3'
includes = ['./include/']
out_dir = 'bin'
default_libs = false
